import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '@styles/Genres.module.css'

import Track from "@components/Track"

export default function Genre({genre, tracks}) {

  return (
    <div className="container">
      <Head>
        <title>Genre</title>
        <meta name="description" content="Generated by create next app" />
        <link el="icon" href="/favicon.ico" />
      </Head>

      <Link href="/"><a>Home</a></Link>

      <main>
        <h1>A genre: {genre}</h1>
        <h2>Recommended Artists</h2>
        <ul className={styles.grid}>
        {tracks.map(track => <Track key={track.id} track={track} />)}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  const data = await fetch("https://api.spotify.com/v1/recommendations/available-genre-seeds", 
  {
    headers:{
      Authorization: `Bearer ${process.env.SPOTIFY_OAUTH_TOKEN}`
    }
  }).then(response => response.json());
  
  const genrePaths = data.genres.map(genre => { return { params: { genre } } });

  return {
    paths: genrePaths,
    fallback: false
  };

}

export async function getStaticProps({params}) {

  const data = await fetch(`https://api.spotify.com/v1/recommendations?seed_genres=${params.genre}`, 
  {
    headers:{
      Authorization: `Bearer ${process.env.SPOTIFY_OAUTH_TOKEN}`
    }
  }).then(response => response.json());

  return {
    props: {
      genre: params.genre,
      tracks: data.tracks
    }
  }
}
