import Head from 'next/head'
import Link from "next/link"

export default function Home({ genres }) {

  return (
    <div className="container">
      <Head>
        <title>Music Recommender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Music Recommender</h1>
        <h2>Recommended Artists</h2>
      </main>
      <aside>
        <h2>Genre List</h2>
        <ul>
          {genres.map(genre => 
          <li key={genre}>
            <Link href={`/${genre}`}>
              <a>{genre}</a>
            </Link>
          </li>)}
        </ul>
      </aside> 
      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export async function getStaticProps() {

  const data = await fetch("https://api.spotify.com/v1/recommendations/available-genre-seeds", 
  {
    headers:{
      Authorization: `Bearer ${process.env.SPOTIFY_OAUTH_TOKEN}`
    }
  }).then(response => response.json());

  console.log(data);

  return {
    props: {
      genres: data.genres
    },
    revalidate: 60
  }
}
